### ISSUE TITLE
Spacemacs sometimes indents things with 4 spaces

### ISSUE THREAD

**Issue by igelstorm** [CultivateHQ/cultivate_shared_config#8]
I've made the title of this issue very generic, because there might be a lot of solutions and I don't want to presuppose anything.

We indent pretty much everything with 2 spaces. Sometimes spacemacs opens a file and decides that it wants to indent with 4 spaces, and that's annoying - especially when it indents automatically as you type.

Possible approaches for fixing/mitigating:

* Make sure the modes we care about are set to use 2 spaces, and that the file types open with the right mode (JS indents with 2 spaces in `web-mode`, but not in `Javascript-IDE` mode, which is the default - setting JS files to open in `web-mode` might be an easy win)
* Set indentation globally, for all modes - might not be possible
* Find out how to turn off auto-indenting, so that you can at least not have your work ruined even if the settings are wrong and you can't find another way around it - obviously a workaround

**Comment by picandocodigo** [comment]
I don't think this has been happening anymore.
