### ISSUE TITLE
Spacemacs crashes frequently with segmentation fault

### ISSUE THREAD

**Issue by igelstorm** [CultivateHQ/cultivate_shared_config#9]
This happens often enough to be annoying and disruptive - especially on Fernando's (Debian) machine, but also on mine. [This issue](https://github.com/syl20bnr/spacemacs/issues/8197) might be related.

**Comment by igelstorm** [comment]
I've been using spacemacs again for a couple of weeks and haven't had this issue at all. Maybe it's fixed?

**Comment by picandocodigo** [comment]
I think it's safe to close this issue. This hasn't happened in my machine for a while, we'll open a new issue if it comes up again.
